server:
  port: 8089
spring:
  application:
    name: notification
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres:2345/notification
    password: pg123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
rabbitmq:
  exchanges:
    internal: internal.exchanges
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-keys